ViewModels/DashBoardViewModel.cs
namespace JwtCookiesScheme.ViewModels
{
    public class DashBoardViewModel
    {
        public ICollection<UserItemViewModel>? users { get; set; }
    }
}

ViewModels/EditViewModels.cs
namespace JwtCookiesScheme.ViewModels
{
    public class EditViewModels
    {

    }
}

ViewModels/UserItemViewModel.cs
namespace JwtCookiesScheme.ViewModels
{
    public class UserItemViewModel
    {
        public string UserName { get; set; } = string.Empty;
        public string UserEmail { get; set; } = string.Empty;
        public string UserPhone { get; set; } = string.Empty;
        public string UserId { get; set; } = string.Empty;
        public List<string> UserRole { get; set; } = new List<string>();
        public string UserFirstName { get; set; } = string.Empty;
        public string UserLastName { get; set; } = string.Empty;
        public string FullName()
        {
            return UserFirstName + UserLastName;
        }

        public string RoleString()
        {
            return string.Join(", ", UserRole);
        }

    }
}

Controllers/AdminController.cs
using AutoMapper;
using JwtCookiesScheme.Dtos;
using JwtCookiesScheme.Interfaces;
using JwtCookiesScheme.Types;
using JwtCookiesScheme.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace JwtCookiesScheme.Controllers
{
    [Authorize(Policy ="AdminOnly")]
    public class AdminController:Controller
    {
        private readonly IAdminService _adminService;
        private readonly IMapper _mapper;
        public AdminController(IAdminService adminService,IMapper mapper) {
            _adminService = adminService;
            _mapper = mapper;   
        }


        [HttpGet]
        public async Task<IActionResult> DashBoard()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier);
            var users = await _adminService.GetDashBoard(userId.Value);
            var userViewModel=_mapper.Map<List<UserItemViewModel>>(users);

            return View(new DashBoardViewModel() { users= userViewModel });
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpGet]
        public  async Task<IActionResult> Edit(string id)
        {
            var userId = id;
            var adminId = User.FindFirst(ClaimTypes.NameIdentifier);
            var users = await _adminService.GetUserData(adminId.Value,userId);
            var userViewModel=_mapper.Map<EditRequest>(users);
            return View(userViewModel);
        }
        //[HttpPost]
        //public async Task<IActionResult> Create()
        //{

        //}
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var userId = id;
                var adminId = User.FindFirst(ClaimTypes.NameIdentifier);
                await _adminService.DeleteDataUser(adminId.Value, userId);
                TempData.Put("Alert",new ErrorMessageViewModel { AlertType = AlertType.info.ToString(), Message = "Delete success" });
                return RedirectToAction("DashBoard");
            }catch 
            {
                TempData.Put("Alert", new ErrorMessageViewModel { AlertType = AlertType.info.ToString(), Message = "Can not delete user." });

                return RedirectToAction("DashBoard");

            }

        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditRequest editRequest)
        {
        if (!ModelState.IsValid) {
            TempData["Alert"] = new ErrorMessageViewModel(){ AlertType=AlertType.info.ToString(),Message="Invalid inputs." };
                return View(editRequest);
            }
            try
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier);
                await _adminService.UpdateUser(userId.Value, editRequest);
                return RedirectToAction("DashBoard");
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
                TempData["Alert"] = new ErrorMessageViewModel() { AlertType = AlertType.warning.ToString(), Message = "Internal error." };
                return View(editRequest);
            }

        }


    }
}

Controllers/UserController.cs
using AutoMapper;
using JwtCookiesScheme.Entities;
using JwtCookiesScheme.Interfaces;
using JwtCookiesScheme.Services;
using JwtCookiesScheme.Types;
using JwtCookiesScheme.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace JwtCookiesScheme.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService<User> _userService;
        private readonly IMapper _mapper;

        public UserController(IUserService<User> userService, IMapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            try
            {
                var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
                var userId = userIdClaim?.Value;
                var claims = User.Claims;
                foreach (var claim in claims)
                {
                    Console.WriteLine(claim.Type + " " + claim.Value);
                }

                if (string.IsNullOrWhiteSpace(userId))
                {
                    TempData["Alert"] = new ErrorMessageViewModel() {Message= "Some errors occured. Please login again." ,AlertType=AlertType.danger.ToString()};
                    HttpContext.Response.Cookies.Delete("accessToken");
                    HttpContext.Response.Cookies.Delete("refreshToken");
                    return RedirectToAction("Login", "Auth");
                }
                ViewData["Title"] = "Profile";
                var userData = await _userService.GetProfile(userId);
                var userView = _mapper.Map<UserViewModel>(userData);
                return View(userView);
            }
            catch (Exception ex)
            {
                TempData["Alert"] = new ErrorMessageViewModel() { Message = ex.Message, AlertType = AlertType.warning.ToString() };
                return View();
            }
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            var userId = userIdClaim?.Value;
            if (string.IsNullOrWhiteSpace(userId))
            {
                return BadRequest("User ID cannot be null or empty.");
            }
            ViewData["Title"] = "Index";
            var userData =await _userService.GetAllUser();
            var userView = _mapper.Map<List<UserViewModel>>(userData);

            return View(userView);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Logout()
        {
            try
            {
                var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
                var userId = userIdClaim?.Value;
                if (string.IsNullOrEmpty(userId))
                {
                    return NotFound("User ID not found in claims.");
                }
                HttpContext.Response.Cookies.Delete("accessToken");
                HttpContext.Response.Cookies.Delete("refreshToken");
                return RedirectToAction("Login","Auth");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

    }
}

Views/Admin/Create.cshtml
@model JwtCookiesScheme.Dtos.RegisterRequest

<h2>Create New User</h2>

<form asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="UserName" class="control-label"></label>
        <input asp-for="UserName" class="form-control" />
        <span asp-validation-for="UserName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserEmail" class="control-label"></label>
        <input asp-for="UserEmail" class="form-control" />
        <span asp-validation-for="UserEmail" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserPassword" class="control-label"></label>
        <input asp-for="UserPassword" type="password" class="form-control" />
        <span asp-validation-for="UserPassword" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ConfirmPassword" class="control-label"></label>
        <input asp-for="ConfirmPassword" type="password" class="form-control" />
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserFirstName" class="control-label"></label>
        <input asp-for="UserFirstName" class="form-control" />
        <span asp-validation-for="UserFirstName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserLastName" class="control-label"></label>
        <input asp-for="UserLastName" class="form-control" />
        <span asp-validation-for="UserLastName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserPhone" class="control-label"></label>
        <input asp-for="UserPhone" class="form-control" />
        <span asp-validation-for="UserPhone" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserRole" class="control-label"></label>
        <select asp-for="UserRole" class="form-control">
            <option value="GUEST">Guest</option>
            <option value="USER">User</option>
            <option value="ADMIN">Admin</option>
        </select>
        <span asp-validation-for="UserRole" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

Views/Admin/DashBoard.cshtml
@model JwtCookiesScheme.ViewModels.DashBoardViewModel
@{
}
<h2>User Dashboard</h2>
<table class="table">
    <thead>
        <tr>
            <th>User Name</th>
            <th>Email</th>
            <th>Full Name</th>
            <th>Phone Number</th>
            <th>Role</th>

            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in @Model.users)
        {
            @await Html.PartialAsync("_UserItem",user);
        }
    </tbody>
</table>
<a href="@Url.Action("Create", "User")">Create New User</a>

Views/Admin/Edit.cshtml
@model JwtCookiesScheme.Dtos.EditRequest

<h2>Edit User</h2>

<partial name="_Validation" />
<form asp-action="Edit" method="post" asp-controller="Admin">

    <div class="form-group">
        <label asp-for="UserEmail" class="control-label"></label>
        <input readonly asp-for="UserEmail" class="form-control" value="@Model.UserEmail" />
        <span asp-validation-for="UserEmail" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserFirstName" class="control-label"></label>
        <input asp-for="UserFirstName" class="form-control" />
        <span asp-validation-for="UserFirstName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserLastName" class="control-label"></label>
        <input asp-for="UserLastName" class="form-control" />
        <span asp-validation-for="UserLastName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserPhone" class="control-label"></label>
        <input asp-for="UserPhone" class="form-control" />
        <span asp-validation-for="UserPhone" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UserRoles" class="control-label">Choose an option</label>
        <select asp-for="UserRoles" class="form-control form-select" asp-items="@Model.RoleList">
        </select>
        <span asp-validation-for="UserRoles" class="text-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary">Save Changes</button>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

</form>

Views/Admin/_UserItem.cshtml
@model JwtCookiesScheme.ViewModels.UserItemViewModel
<tr>
    <td>@Model.UserName</td>
    <td>@Model.UserEmail</td>
    <td>@Model.FullName()</td>
    <td>@Model.UserPhone</td>
    <td>@Model.RoleString()</td>

    <td>
        <a asp-action="Edit" asp-controller="Admin" asp-route-id="@Model.UserId" >Edit</a> |
        <a asp-action="Delete" asp-controller="Admin" asp-route-id="@Model.UserId">Delete</a>
    </td>
</tr>